title: Tombout
description: Passionated Zombie
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "googleb7aae16e0112ddf6.html"
    values:
      sitemap: false
